# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xcvu9p-flga2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Vivado_prj/B-CEDNet/B-CEDNet.cache/wt [current_project]
set_property parent.project_path F:/Vivado_prj/B-CEDNet/B-CEDNet.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vcu118:part0:2.0 [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM.xci
set_property used_in_implementation false [get_files -all f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top data_in_ROM -part xcvu9p-flga2104-2L-e -mode out_of_context

rename_ref -prefix_all data_in_ROM_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef data_in_ROM.dcp
create_report "data_in_ROM_synth_1_synth_report_utilization_0" "report_utilization -file data_in_ROM_utilization_synth.rpt -pb data_in_ROM_utilization_synth.pb"

if { [catch {
  file copy -force F:/Vivado_prj/B-CEDNet/B-CEDNet.runs/data_in_ROM_synth_1/data_in_ROM.dcp f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir F:/Vivado_prj/B-CEDNet/B-CEDNet.ip_user_files/ip/data_in_ROM]} {
  catch { 
    file copy -force f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_stub.v F:/Vivado_prj/B-CEDNet/B-CEDNet.ip_user_files/ip/data_in_ROM
  }
}

if {[file isdir F:/Vivado_prj/B-CEDNet/B-CEDNet.ip_user_files/ip/data_in_ROM]} {
  catch { 
    file copy -force f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_stub.vhdl F:/Vivado_prj/B-CEDNet/B-CEDNet.ip_user_files/ip/data_in_ROM
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
