# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM.xci
# IP: The module: 'data_in_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_in_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM.xci
# IP: The module: 'data_in_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/sources_1/ip/data_in_ROM/data_in_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_in_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
