# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu9p-flga2104-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivado_prj/B-CEDNet/B-CEDNet.cache/wt [current_project]
set_property parent.project_path F:/Vivado_prj/B-CEDNet/B-CEDNet.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vcu118:part0:2.0 [current_project]
set_property ip_cache_permissions disable [current_project]
add_files F:/Vivado_prj/B-CEDNet/src/data_in.coe
read_verilog {
  F:/Vivado_prj/B-CEDNet/src/soft_ip/include/includes.vh
  F:/Vivado_prj/B-CEDNet/src/soft_ip/include/util.vh
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/headers/gen/W_ROM_SOFT_F.vh
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/headers/gen/W_ROM_SOFT.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/EC_4.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/EC_3.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_5.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/TOP.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/EC_2.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/AD.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/EC_1.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_6.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_7.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_8.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_9.vh
  F:/Vivado_prj/B-CEDNet/src/testbench/headers/DC_10.vh
}
read_verilog -library xil_defaultlib -sv {
  F:/Vivado_prj/B-CEDNet/src/soft_ip/AD_CTRL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_ADAPTER.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_DECODER.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_DECODER_OUT.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_ENCODER.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_ENDECODER.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BINCONV_KERNEL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/COMPARATOR.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/CONV_KERNEL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/DC_CTRL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/DEMUX.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/EC_CTRL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/EDC_CTRL.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/FMAP_IN_SHIFTREG.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/FMAP_OUT_SHIFTREG.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/INDEX_SRAM.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/PE_DC.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/PE_EC.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/PE_EDC.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/PE_FP.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/PE_OUT.v
  F:/Vivado_prj/src/soft_ip/mem/gen/ROM_CORE_TEST_0.sv
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/ROM_SOFT_F.v
  F:/Vivado_prj/src/soft_ip/mem/gen/TOP_MEAN_ROM_0.sv
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/W_ROM.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/W_ROM_1024X32X32.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/W_ROM_512X64X16.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/W_ROM_SOFT.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/fifo1.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/BCEDN_TOP.v
}
read_verilog -library xil_defaultlib {
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_W_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_W_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_W_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/AD_W_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_10_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_10_REF_SCALE_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_10_W_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_5_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_6_W_ROM_F_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_REF_SIGN_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_7_W_ROM_F_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_REF_SIGN_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_8_W_ROM_F_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_REF_SIGN_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/DC_9_W_ROM_9.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/DEMUX_1b.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_REF_SIGN_ROM_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_10.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_11.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_12.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_13.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_14.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_15.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_8.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_1_W_ROM_F_9.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_REF_SIGN_ROM_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_4.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_5.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_6.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_2_W_ROM_F_7.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SOFT_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SOFT_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SOFT_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_REF_SOFT_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_3_W_ROM_F_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SIGN_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SIGN_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SIGN_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SIGN_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SOFT_ROM_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SOFT_ROM_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SOFT_ROM_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_REF_SOFT_ROM_3.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_W_ROM_F_0.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_W_ROM_F_1.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_W_ROM_F_2.v
  F:/Vivado_prj/BCEDNet_verify_matlab/src/soft_ip/mem/gen/EC_4_W_ROM_F_3.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/mem/b7dhd110g_1024x32x32.beh.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/mem/b7dhd110g_512x64x16.beh.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/fifomem.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/mem/mem2p11_dxw_p.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/rptr_empty.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/sync_r2w.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/sync_w2r.v
  F:/Vivado_prj/B-CEDNet/src/soft_ip/building_blocks/wptr_full.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/constrs_1/new/sys_top.xdc
set_property used_in_implementation false [get_files F:/Vivado_prj/B-CEDNet/B-CEDNet.srcs/constrs_1/new/sys_top.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top BCEDN_TOP -part xcvu9p-flga2104-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BCEDN_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BCEDN_TOP_utilization_synth.rpt -pb BCEDN_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
