create_clock -period 20.0 -name clk -waveform {0.0 10.0} -add [get_ports clk]
#set_property PACKAGE_PIN L19 [get_ports rst]
#set_property IOSTANDARD LVCMOS12 [get_ports rst]
#set_property IOSTANDARD DIFF_SSTL12 [get_ports clk_n]
#set_property PACKAGE_PIN E12 [get_ports clk_p]
#set_property PACKAGE_PIN D12 [get_ports clk_n]
#set_property IOSTANDARD DIFF_SSTL12 [get_ports clk_p]
#set_property PACKAGE_PIN AT32 [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[0]}]
#set_property PACKAGE_PIN AV34 [get_ports {led[1]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[1]}]
#set_property PACKAGE_PIN AY30 [get_ports {led[2]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[2]}]
#set_property PACKAGE_PIN BB32 [get_ports {led[3]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[3]}]
#set_property PACKAGE_PIN BF32 [get_ports {led[4]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[4]}]
#set_property PACKAGE_PIN AU37 [get_ports {led[5]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[5]}]
#set_property PACKAGE_PIN AV36 [get_ports {led[6]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[6]}]
#set_property PACKAGE_PIN BA37 [get_ports {led[7]}]
#set_property IOSTANDARD LVCMOS12 [get_ports {led[7]}]

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list sys_clk/inst/clk_out1]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 17 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {data_out_count_reg[0]} {data_out_count_reg[1]} {data_out_count_reg[2]} {data_out_count_reg[3]} {data_out_count_reg[4]} {data_out_count_reg[5]} {data_out_count_reg[6]} {data_out_count_reg[7]} {data_out_count_reg[8]} {data_out_count_reg[9]} {data_out_count_reg[10]} {data_out_count_reg[11]} {data_out_count_reg[12]} {data_out_count_reg[13]} {data_out_count_reg[14]} {data_out_count_reg[15]} {data_out_count_reg[16]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 12 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {data_in_addr_reg__0[0]} {data_in_addr_reg__0[1]} {data_in_addr_reg__0[2]} {data_in_addr_reg__0[3]} {data_in_addr_reg__0[4]} {data_in_addr_reg__0[5]} {data_in_addr_reg__0[6]} {data_in_addr_reg__0[7]} {data_in_addr_reg__0[8]} {data_in_addr_reg__0[9]} {data_in_addr_reg__0[10]} {data_in_addr_reg__0[11]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 32 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {latency_count[0]} {latency_count[1]} {latency_count[2]} {latency_count[3]} {latency_count[4]} {latency_count[5]} {latency_count[6]} {latency_count[7]} {latency_count[8]} {latency_count[9]} {latency_count[10]} {latency_count[11]} {latency_count[12]} {latency_count[13]} {latency_count[14]} {latency_count[15]} {latency_count[16]} {latency_count[17]} {latency_count[18]} {latency_count[19]} {latency_count[20]} {latency_count[21]} {latency_count[22]} {latency_count[23]} {latency_count[24]} {latency_count[25]} {latency_count[26]} {latency_count[27]} {latency_count[28]} {latency_count[29]} {latency_count[30]} {latency_count[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 32 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {fps_count[0]} {fps_count[1]} {fps_count[2]} {fps_count[3]} {fps_count[4]} {fps_count[5]} {fps_count[6]} {fps_count[7]} {fps_count[8]} {fps_count[9]} {fps_count[10]} {fps_count[11]} {fps_count[12]} {fps_count[13]} {fps_count[14]} {fps_count[15]} {fps_count[16]} {fps_count[17]} {fps_count[18]} {fps_count[19]} {fps_count[20]} {fps_count[21]} {fps_count[22]} {fps_count[23]} {fps_count[24]} {fps_count[25]} {fps_count[26]} {fps_count[27]} {fps_count[28]} {fps_count[29]} {fps_count[30]} {fps_count[31]}]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk]
